name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master # https://github.com/marketplace/actions/push-to-ghcr
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Console Mode
        run: |
          echo "Testing console mode..."
          docker run --rm ghcr.io/${{ github.repository }}:latest https://www.example.com > output.html
          if grep -q "<title>Example Domain</title>" output.html; then
            echo "Console mode test passed."
          else
            echo "Console mode test failed."
            exit 1
          fi

      - name: Test HTTP Server Mode
        run: |
          echo "Testing HTTP server mode..."
          docker run --name testcontainer -d -p 3000:3000 ghcr.io/${{ github.repository }}:latest serve
          sleep 30
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d '{"url":"https://www.example.com"}' http://localhost:3000/scrape)
          echo $RESPONSE
          docker stop testcontainer
          if echo "$RESPONSE" | grep -q "<title>Example Domain</title>"; then
            echo "HTTP server mode test passed."
          else
            echo "HTTP server mode test failed."
            exit 1
          fi
